"""Added quote and author to quote-table

Revision ID: a0459fed0538
Revises: 14de25ec54b9
Create Date: 2019-11-11 12:25:08.503877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0459fed0538'
down_revision = '14de25ec54b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quote', sa.Column('author', sa.String(length=300), nullable=True))
    op.add_column('quote', sa.Column('quote', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quote', 'quote')
    op.drop_column('quote', 'author')
    # ### end Alembic commands ###
